/**
 * MERO Compiler - Luau Code Generator Implementation
 * Developer: MERO:TG@QP4RM
 */
#include "codegen_luau.h"
#include <algorithm>

namespace mero {

LuauCodegen::LuauCodegen(const CodegenOptions& opts) : opts_(opts) {
    init_builtin_map();
}

void LuauCodegen::init_builtin_map() {
    python_to_luau_ = {
        {"print", "_RT.print"},
        {"len", "_RT.len"},
        {"range", "_RT.range"},
        {"int", "_RT.to_int"},
        {"float", "_RT.to_float"},
        {"str", "_RT.to_str"},
        {"bool", "_RT.to_bool"},
        {"type", "_RT.type_of"},
        {"isinstance", "_RT.isinstance"},
        {"abs", "math.abs"},
        {"max", "math.max"},
        {"min", "math.min"},
        {"round", "math.round"},
        {"input", "_RT.input"},
        {"enumerate", "_RT.enumerate"},
        {"zip", "_RT.zip"},
        {"map", "_RT.map"},
        {"filter", "_RT.filter"},
        {"sorted", "_RT.sorted"},
        {"reversed", "_RT.reversed"},
        {"sum", "_RT.sum"},
        {"any", "_RT.any"},
        {"all", "_RT.all"},
        {"list", "_RT.to_list"},
        {"dict", "_RT.to_dict"},
        {"set", "_RT.to_set"},
        {"tuple", "_RT.to_tuple"},
        {"hasattr", "_RT.hasattr"},
        {"getattr", "_RT.getattr"},
        {"setattr", "_RT.setattr"},
        {"chr", "string.char"},
        {"ord", "string.byte"},
        {"hex", "_RT.hex"},
        {"oct", "_RT.oct"},
        {"bin", "_RT.bin"},
        {"id", "_RT.id"},
        {"hash", "_RT.hash"},
        {"repr", "_RT.repr"},
        {"iter", "_RT.iter"},
        {"next", "_RT.next"},
        {"super", "_RT.super"},
        {"format", "_RT.format"},
    };
}

std::string LuauCodegen::generate(ir::IRModule* module) {
    output_.clear();
    indent_level_ = 0;

    emit_header();
    emit_runtime_require();
    emit_body(module->body);
    emit_footer(module);

    return output_;
}

void LuauCodegen::emit(const std::string& code) {
    output_ += code;
}

void LuauCodegen::emit_line(const std::string& code) {
    emit_indent();
    output_ += code;
    output_ += "\n";
}

void LuauCodegen::emit_indent() {
    if (opts_.minify) return;
    for (int i = 0; i < indent_level_ * opts_.indent_size; i++) {
        output_ += ' ';
    }
}

void LuauCodegen::emit_newline() {
    if (!opts_.minify) output_ += "\n";
}

void LuauCodegen::indent() { indent_level_++; }
void LuauCodegen::dedent() { if (indent_level_ > 0) indent_level_--; }

std::string LuauCodegen::get_indent() const {
    return std::string(indent_level_ * opts_.indent_size, ' ');
}

void LuauCodegen::emit_header() {
    if (opts_.emit_comments && !opts_.minify) {
        emit_line("--!strict");
        emit_line("-- Generated by MERO Compiler v1.0");
        emit_line("-- Python to Luau transpilation output");
        emit_line("-- Developer: MERO:TG@QP4RM");
        emit_newline();
    }
}

void LuauCodegen::emit_runtime_require() {
    emit_line("local _RT = require(script.Parent:WaitForChild(\"MeroRuntime\"))");
    emit_newline();
}

void LuauCodegen::emit_body(const ir::IRNodeList& body) {
    for (auto& node : body) {
        if (node) emit_node(node.get());
    }
}

void LuauCodegen::emit_footer(ir::IRModule* module) {
    if (!module->exports.empty()) {
        emit_newline();
        emit_line("return {");
        indent();
        for (auto& exp : module->exports) {
            emit_line(exp + " = " + exp + ",");
        }
        dedent();
        emit_line("}");
    }
}

void LuauCodegen::emit_node(ir::IRNode* node) {
    switch (node->kind) {
        case ir::IRKind::Function: emit_function(static_cast<ir::IRFunction*>(node)); break;
        case ir::IRKind::Class: emit_class(static_cast<ir::IRClass*>(node)); break;
        case ir::IRKind::If: emit_if(static_cast<ir::IRIf*>(node)); break;
        case ir::IRKind::While: emit_while(static_cast<ir::IRWhile*>(node)); break;
        case ir::IRKind::ForNumeric: emit_for_numeric(static_cast<ir::IRForNumeric*>(node)); break;
        case ir::IRKind::ForIn: emit_for_in(static_cast<ir::IRForIn*>(node)); break;
        case ir::IRKind::Assign: emit_assign(static_cast<ir::IRAssign*>(node)); break;
        case ir::IRKind::AugAssign: emit_aug_assign(static_cast<ir::IRAugAssign*>(node)); break;
        case ir::IRKind::Return: emit_return(static_cast<ir::IRReturn*>(node)); break;
        case ir::IRKind::Try: emit_try(static_cast<ir::IRTry*>(node)); break;
        case ir::IRKind::Throw: emit_throw(static_cast<ir::IRThrow*>(node)); break;
        case ir::IRKind::ExprStmt: emit_expr_stmt(static_cast<ir::IRExprStmt*>(node)); break;
        case ir::IRKind::Break: emit_line("break"); break;
        case ir::IRKind::Continue: emit_line("continue"); break;
        case ir::IRKind::Comment:
            if (opts_.emit_comments) {
                emit_line("-- " + static_cast<ir::IRComment*>(node)->text);
            }
            break;
        case ir::IRKind::Global: break; // Handled differently
        default: break;
    }
}

void LuauCodegen::emit_function(ir::IRFunction* node) {
    std::string prefix = node->is_local ? "local " : "";
    std::string params;
    for (size_t i = 0; i < node->params.size(); i++) {
        if (node->is_method && i == 0 && node->params[i].name == "self") continue;
        if (!params.empty()) params += ", ";
        params += node->params[i].name;
        if (node->params[i].variadic) params = "...";
    }

    emit_line(prefix + "function " + node->name + "(" + params + ")");
    indent();

    // Default parameter values
    for (auto& param : node->params) {
        if (param.default_val) {
            emit_line("if " + param.name + " == nil then " +
                     param.name + " = " + emit_expr(param.default_val.get()) + " end");
        }
    }

    emit_body(node->body);
    dedent();
    emit_line("end");
    emit_newline();
}

void LuauCodegen::emit_class(ir::IRClass* node) {
    emit_line("local " + node->name + " = {}");
    emit_line(node->name + ".__index = " + node->name);

    if (!node->base.empty()) {
        emit_line("setmetatable(" + node->name + ", {__index = " + node->base + "})");
    }

    emit_newline();

    // Constructor
    bool has_init = false;
    for (auto& method : node->methods) {
        if (method->name == "__init__") {
            has_init = true;
            std::string params;
            for (size_t i = 1; i < method->params.size(); i++) {
                if (!params.empty()) params += ", ";
                params += method->params[i].name;
            }

            emit_line("function " + node->name + ".new(" + params + ")");
            indent();
            if (node->base.empty()) {
                emit_line("local self = setmetatable({}, " + node->name + ")");
            } else {
                emit_line("local self = setmetatable(" + node->base + ".new(), " + node->name + ")");
            }
            emit_body(method->body);
            emit_line("return self");
            dedent();
            emit_line("end");
            emit_newline();
            break;
        }
    }

    if (!has_init) {
        emit_line("function " + node->name + ".new()");
        indent();
        emit_line("local self = setmetatable({}, " + node->name + ")");
        emit_line("return self");
        dedent();
        emit_line("end");
        emit_newline();
    }

    // Other methods
    for (auto& method : node->methods) {
        if (method->name == "__init__") continue;

        std::string lua_name = method->name;
        // Python dunder methods mapping
        if (lua_name == "__str__") lua_name = "__tostring";
        else if (lua_name == "__len__") lua_name = "__len";
        else if (lua_name == "__add__") lua_name = "__add";
        else if (lua_name == "__sub__") lua_name = "__sub";
        else if (lua_name == "__mul__") lua_name = "__mul";
        else if (lua_name == "__eq__") lua_name = "__eq";
        else if (lua_name == "__lt__") lua_name = "__lt";

        std::string params;
        for (size_t i = 1; i < method->params.size(); i++) {
            if (!params.empty()) params += ", ";
            params += method->params[i].name;
        }

        emit_line("function " + node->name + ":" + lua_name + "(" + params + ")");
        indent();
        emit_body(method->body);
        dedent();
        emit_line("end");
        emit_newline();
    }
}

void LuauCodegen::emit_if(ir::IRIf* node) {
    emit_line("if " + emit_expr(node->condition.get()) + " then");
    indent();
    emit_body(node->then_body);
    dedent();

    for (auto& [cond, elif_body] : node->elifs) {
        emit_line("elseif " + emit_expr(cond.get()) + " then");
        indent();
        emit_body(elif_body);
        dedent();
    }

    if (!node->else_body.empty()) {
        emit_line("else");
        indent();
        emit_body(node->else_body);
        dedent();
    }

    emit_line("end");
}

void LuauCodegen::emit_while(ir::IRWhile* node) {
    emit_line("while " + emit_expr(node->condition.get()) + " do");
    indent();
    emit_body(node->body);
    dedent();
    emit_line("end");
}

void LuauCodegen::emit_for_numeric(ir::IRForNumeric* node) {
    std::string step = node->step ? ", " + emit_expr(node->step.get()) : "";
    emit_line("for " + node->var + " = " +
             emit_expr(node->start.get()) + ", " +
             emit_expr(node->stop.get()) + step + " do");
    indent();
    emit_body(node->body);
    dedent();
    emit_line("end");
}

void LuauCodegen::emit_for_in(ir::IRForIn* node) {
    std::string vars;
    for (size_t i = 0; i < node->vars.size(); i++) {
        if (i > 0) vars += ", ";
        vars += node->vars[i];
    }

    std::string iter_expr = emit_expr(node->iterator.get());

    // Detect range() calls for numeric for loops
    if (node->iterator && node->iterator->kind == ir::IRKind::Call) {
        auto* call = static_cast<ir::IRCall*>(node->iterator.get());
        if (call->callee && call->callee->kind == ir::IRKind::Ident) {
            auto* name = static_cast<ir::IRIdent*>(call->callee.get());
            if (name->name == "range") {
                // Convert to numeric for
                if (call->args.size() == 1) {
                    emit_line("for " + vars + " = 0, " + emit_expr(call->args[0].get()) + " - 1 do");
                } else if (call->args.size() == 2) {
                    emit_line("for " + vars + " = " + emit_expr(call->args[0].get()) + ", " +
                             emit_expr(call->args[1].get()) + " - 1 do");
                } else if (call->args.size() == 3) {
                    emit_line("for " + vars + " = " + emit_expr(call->args[0].get()) + ", " +
                             emit_expr(call->args[1].get()) + " - 1, " +
                             emit_expr(call->args[2].get()) + " do");
                }
                indent();
                emit_body(node->body);
                dedent();
                emit_line("end");
                return;
            }
        }
    }

    emit_line("for " + vars + " in " + iter_expr + " do");
    indent();
    emit_body(node->body);
    dedent();
    emit_line("end");
}

void LuauCodegen::emit_assign(ir::IRAssign* node) {
    std::string target = emit_expr(node->target.get());
    std::string value = emit_expr(node->value.get());
    std::string prefix = node->is_local ? "local " : "";
    emit_line(prefix + target + " = " + value);
}

void LuauCodegen::emit_aug_assign(ir::IRAugAssign* node) {
    std::string target = emit_expr(node->target.get());
    std::string value = emit_expr(node->value.get());
    std::string op = map_operator(node->op);

    if (node->op == ir::OpCode::Pow) {
        emit_line(target + " = " + target + " ^ " + value);
    } else if (node->op == ir::OpCode::FloorDiv) {
        emit_line(target + " = math.floor(" + target + " / " + value + ")");
    } else {
        emit_line(target + " " + op + "= " + value);
    }
}

void LuauCodegen::emit_return(ir::IRReturn* node) {
    if (node->values.empty()) {
        emit_line("return");
    } else if (node->values.size() == 1) {
        emit_line("return " + emit_expr(node->values[0].get()));
    } else {
        std::string vals;
        for (size_t i = 0; i < node->values.size(); i++) {
            if (i > 0) vals += ", ";
            vals += emit_expr(node->values[i].get());
        }
        emit_line("return " + vals);
    }
}

void LuauCodegen::emit_try(ir::IRTry* node) {
    emit_line("local _ok, _err = pcall(function()");
    indent();
    emit_body(node->body);
    dedent();
    emit_line("end)");

    if (!node->handlers.empty()) {
        emit_line("if not _ok then");
        indent();
        for (auto& handler : node->handlers) {
            if (!handler.name.empty()) {
                emit_line("local " + handler.name + " = _err");
            }
            emit_body(handler.body);
        }
        dedent();
        emit_line("end");
    }

    if (!node->finally_body.empty()) {
        emit_body(node->finally_body);
    }
}

void LuauCodegen::emit_throw(ir::IRThrow* node) {
    if (node->exception) {
        emit_line("error(" + emit_expr(node->exception.get()) + ")");
    } else {
        emit_line("error(\"unhandled exception\")");
    }
}

void LuauCodegen::emit_expr_stmt(ir::IRExprStmt* node) {
    if (node->expr) {
        emit_line(emit_expr(node->expr.get()));
    }
}

// --- Expression emission ---

std::string LuauCodegen::emit_expr(ir::IRNode* node) {
    if (!node) return "nil";
    switch (node->kind) {
        case ir::IRKind::Literal: return emit_literal(static_cast<ir::IRLiteral*>(node));
        case ir::IRKind::Ident: return emit_ident(static_cast<ir::IRIdent*>(node));
        case ir::IRKind::BinOp: return emit_binop(static_cast<ir::IRBinOp*>(node));
        case ir::IRKind::UnaryOp: return emit_unaryop(static_cast<ir::IRUnaryOp*>(node));
        case ir::IRKind::Call: return emit_call(static_cast<ir::IRCall*>(node));
        case ir::IRKind::MethodCall: return emit_method_call(static_cast<ir::IRMethodCall*>(node));
        case ir::IRKind::Index: return emit_index(static_cast<ir::IRIndex*>(node));
        case ir::IRKind::Field: return emit_field(static_cast<ir::IRField*>(node));
        case ir::IRKind::Array: return emit_array(static_cast<ir::IRArray*>(node));
        case ir::IRKind::Table: return emit_table(static_cast<ir::IRTable*>(node));
        case ir::IRKind::Lambda: return emit_lambda(static_cast<ir::IRLambda*>(node));
        case ir::IRKind::Ternary: return emit_ternary(static_cast<ir::IRTernary*>(node));
        case ir::IRKind::FString: return emit_fstring(static_cast<ir::IRFString*>(node));
        case ir::IRKind::Comprehension: return emit_comprehension(static_cast<ir::IRComprehension*>(node));
        case ir::IRKind::Slice: return emit_slice(static_cast<ir::IRSlice*>(node));
        default: return "nil --[[ unsupported expr ]]";
    }
}

std::string LuauCodegen::emit_literal(ir::IRLiteral* node) {
    switch (node->lit_kind) {
        case ir::IRLiteral::LNil: return "nil";
        case ir::IRLiteral::LBool:
            return (node->value == "True" || node->value == "true") ? "true" : "false";
        case ir::IRLiteral::LInt: return node->value;
        case ir::IRLiteral::LFloat: return node->value;
        case ir::IRLiteral::LString: return "\"" + escape_string(node->value) + "\"";
        default: return "nil";
    }
}

std::string LuauCodegen::emit_ident(ir::IRIdent* node) {
    if (node->name == "self") return "self";
    if (node->name == "True") return "true";
    if (node->name == "False") return "false";
    if (node->name == "None") return "nil";
    return node->name;
}

std::string LuauCodegen::emit_binop(ir::IRBinOp* node) {
    std::string left = emit_expr(node->left.get());
    std::string right = emit_expr(node->right.get());

    switch (node->op) {
        case ir::OpCode::Add: return "(" + left + " + " + right + ")";
        case ir::OpCode::Sub: return "(" + left + " - " + right + ")";
        case ir::OpCode::Mul: return "(" + left + " * " + right + ")";
        case ir::OpCode::Div: return "(" + left + " / " + right + ")";
        case ir::OpCode::FloorDiv: return "math.floor(" + left + " / " + right + ")";
        case ir::OpCode::Mod: return "(" + left + " % " + right + ")";
        case ir::OpCode::Pow: return "(" + left + " ^ " + right + ")";
        case ir::OpCode::Eq: return "(" + left + " == " + right + ")";
        case ir::OpCode::Neq: return "(" + left + " ~= " + right + ")";
        case ir::OpCode::Lt: return "(" + left + " < " + right + ")";
        case ir::OpCode::Gt: return "(" + left + " > " + right + ")";
        case ir::OpCode::Lte: return "(" + left + " <= " + right + ")";
        case ir::OpCode::Gte: return "(" + left + " >= " + right + ")";
        case ir::OpCode::And: return "(" + left + " and " + right + ")";
        case ir::OpCode::Or: return "(" + left + " or " + right + ")";
        case ir::OpCode::Concat: return "(" + left + " .. " + right + ")";
        case ir::OpCode::BitAnd: return "bit32.band(" + left + ", " + right + ")";
        case ir::OpCode::BitOr: return "bit32.bor(" + left + ", " + right + ")";
        case ir::OpCode::BitXor: return "bit32.bxor(" + left + ", " + right + ")";
        case ir::OpCode::Shl: return "bit32.lshift(" + left + ", " + right + ")";
        case ir::OpCode::Shr: return "bit32.rshift(" + left + ", " + right + ")";
        default: return "(" + left + " + " + right + ")";
    }
}

std::string LuauCodegen::emit_unaryop(ir::IRUnaryOp* node) {
    std::string operand = emit_expr(node->operand.get());
    switch (node->op) {
        case ir::OpCode::Neg: return "(-" + operand + ")";
        case ir::OpCode::Not: return "(not " + operand + ")";
        case ir::OpCode::BitNot: return "bit32.bnot(" + operand + ")";
        case ir::OpCode::Length: return "#" + operand;
        default: return operand;
    }
}

std::string LuauCodegen::emit_call(ir::IRCall* node) {
    std::string func = emit_expr(node->callee.get());

    // Builtin function mapping
    auto it = python_to_luau_.find(func);
    if (it != python_to_luau_.end()) {
        func = it->second;
        used_builtins_.insert(func);
    }

    std::string args;
    for (size_t i = 0; i < node->args.size(); i++) {
        if (i > 0) args += ", ";
        args += emit_expr(node->args[i].get());
    }
    for (auto& [key, val] : node->kwargs) {
        // kwargs become table argument in Luau
        if (!args.empty()) args += ", ";
        if (!key.empty()) {
            args += "{" + key + " = " + emit_expr(val.get()) + "}";
        } else {
            args += emit_expr(val.get());
        }
    }

    return func + "(" + args + ")";
}

std::string LuauCodegen::emit_method_call(ir::IRMethodCall* node) {
    std::string obj = emit_expr(node->object.get());
    std::string args;
    for (size_t i = 0; i < node->args.size(); i++) {
        if (i > 0) args += ", ";
        args += emit_expr(node->args[i].get());
    }
    return obj + ":" + node->method + "(" + args + ")";
}

std::string LuauCodegen::emit_index(ir::IRIndex* node) {
    std::string obj = emit_expr(node->object.get());
    std::string idx = emit_expr(node->index.get());
    // Python uses 0-based indexing, Luau uses 1-based
    return obj + "[" + idx + " + 1]";
}

std::string LuauCodegen::emit_field(ir::IRField* node) {
    std::string obj = emit_expr(node->object.get());
    return obj + "." + node->field;
}

std::string LuauCodegen::emit_array(ir::IRArray* node) {
    std::string elts;
    for (size_t i = 0; i < node->elements.size(); i++) {
        if (i > 0) elts += ", ";
        elts += emit_expr(node->elements[i].get());
    }
    return "{" + elts + "}";
}

std::string LuauCodegen::emit_table(ir::IRTable* node) {
    if (node->pairs.empty()) return "{}";
    std::string pairs;
    for (size_t i = 0; i < node->pairs.size(); i++) {
        if (i > 0) pairs += ", ";
        std::string key = emit_expr(node->pairs[i].first.get());
        std::string val = emit_expr(node->pairs[i].second.get());
        pairs += "[" + key + "] = " + val;
    }
    return "{" + pairs + "}";
}

std::string LuauCodegen::emit_lambda(ir::IRLambda* node) {
    std::string params;
    for (size_t i = 0; i < node->params.size(); i++) {
        if (i > 0) params += ", ";
        params += node->params[i].name;
    }
    std::string body;
    if (node->body.size() == 1 && node->body[0]->kind == ir::IRKind::Return) {
        auto* ret = static_cast<ir::IRReturn*>(node->body[0].get());
        if (!ret->values.empty()) {
            body = "return " + emit_expr(ret->values[0].get());
        }
    }
    return "function(" + params + ") " + body + " end";
}

std::string LuauCodegen::emit_ternary(ir::IRTernary* node) {
    std::string cond = emit_expr(node->condition.get());
    std::string t = emit_expr(node->true_val.get());
    std::string f = emit_expr(node->false_val.get());
    return "(if " + cond + " then " + t + " else " + f + ")";
}

std::string LuauCodegen::emit_fstring(ir::IRFString* node) {
    std::string result;
    for (size_t i = 0; i < node->parts.size(); i++) {
        if (i > 0) result += " .. ";
        auto& part = node->parts[i];
        if (part->kind == ir::IRKind::Literal) {
            result += emit_literal(static_cast<ir::IRLiteral*>(part.get()));
        } else {
            result += "tostring(" + emit_expr(part.get()) + ")";
        }
    }
    return result.empty() ? "\"\"" : result;
}

std::string LuauCodegen::emit_comprehension(ir::IRComprehension* node) {
    // List comprehension -> table.create with loop
    std::string iter = emit_expr(node->iterator.get());
    std::string elem = emit_expr(node->element.get());
    std::string var = node->variable;

    std::string result = "(function() local _r = {} for _, " + var + " in " + iter + " do ";
    if (!node->conditions.empty()) {
        result += "if " + emit_expr(node->conditions[0].get()) + " then ";
        result += "table.insert(_r, " + elem + ") end";
    } else {
        result += "table.insert(_r, " + elem + ")";
    }
    result += " end return _r end)()";
    return result;
}

std::string LuauCodegen::emit_slice(ir::IRSlice* node) {
    std::string obj = node->object ? emit_expr(node->object.get()) : "nil";
    std::string lower = node->lower ? emit_expr(node->lower.get()) : "1";
    std::string upper = node->upper ? emit_expr(node->upper.get()) : "#" + obj;
    return "_RT.slice(" + obj + ", " + lower + ", " + upper + ")";
}

std::string LuauCodegen::map_operator(ir::OpCode op) {
    switch (op) {
        case ir::OpCode::Add: return "+";
        case ir::OpCode::Sub: return "-";
        case ir::OpCode::Mul: return "*";
        case ir::OpCode::Div: return "/";
        case ir::OpCode::Mod: return "%";
        case ir::OpCode::Pow: return "^";
        default: return "+";
    }
}

std::string LuauCodegen::escape_string(const std::string& str) {
    std::string result;
    for (char c : str) {
        switch (c) {
            case '"': result += "\\\""; break;
            case '\\': result += "\\\\"; break;
            case '\n': result += "\\n"; break;
            case '\t': result += "\\t"; break;
            case '\r': result += "\\r"; break;
            case '\0': result += "\\0"; break;
            default: result += c;
        }
    }
    return result;
}

bool LuauCodegen::is_builtin_function(const std::string& name) {
    return python_to_luau_.count(name) > 0;
}

} // namespace mero
