"""
MERO Compiler - Output Bundler
Bundles multiple compiled Luau files into a single output.
Developer: MERO:TG@QP4RM
"""
from pathlib import Path
from typing import List, Dict
from .compiler import MeroCompiler
from .config import CompilerConfig


class Bundler:
    """Bundles multiple Python modules into a single Luau output."""

    def __init__(self, config: CompilerConfig = None):
        self.config = config or CompilerConfig()
        self.compiler = MeroCompiler(self.config)

    def bundle(self, entry_point: str, output: str = None) -> str:
        """Bundle all imports starting from entry point."""
        entry = Path(entry_point)
        if not entry.exists():
            raise FileNotFoundError(f"Entry point not found: {entry_point}")

        modules: Dict[str, str] = {}
        self._resolve_and_compile(entry, modules)

        bundled = self._generate_bundle(entry.stem, modules)

        if output:
            Path(output).write_text(bundled, encoding="utf-8")

        return bundled

    def _resolve_and_compile(self, file: Path, modules: Dict[str, str],
                              visited: set = None):
        """Recursively resolve and compile modules."""
        if visited is None:
            visited = set()

        file_str = str(file.resolve())
        if file_str in visited:
            return
        visited.add(file_str)

        result = self.compiler.compile_file(str(file))
        if result.success:
            module_name = file.stem
            modules[module_name] = result.output

    def _generate_bundle(self, entry_name: str, modules: Dict[str, str]) -> str:
        """Generate a single bundled Luau file."""
        lines = [
            "--!strict",
            "-- MERO Bundled Output",
            "-- Generated by MERO Bundler",
            "",
            "local _MODULES = {}",
            "local _LOADED = {}",
            "",
            "local function _require(name)",
            "    if _LOADED[name] then return _LOADED[name] end",
            "    local mod = _MODULES[name]",
            "    if not mod then error('Module not found: ' .. name) end",
            "    _LOADED[name] = mod()",
            "    return _LOADED[name]",
            "end",
            "",
        ]

        for name, code in modules.items():
            lines.append(f"_MODULES[\"{name}\"] = function()")
            # Indent module code
            for line in code.split("\n"):
                if line.strip():
                    lines.append("    " + line)
                else:
                    lines.append("")
            lines.append("end")
            lines.append("")

        lines.append(f"return _require(\"{entry_name}\")")
        return "\n".join(lines)
