"""
MERO Compiler - Pure Python Fallback Compiler
Used when the native C++ backend is not available.
Developer: MERO:TG@QP4RM
"""
import ast as python_ast
from typing import List
from .config import CompilerConfig


class CompileResult:
    def __init__(self):
        self.output = ""
        self.success = False
        self.errors: List[str] = []
        self.warnings: List[str] = []
        self.stats = {}


class FallbackCompiler:
    """Pure Python implementation of Python-to-Luau compiler."""

    def __init__(self, config: CompilerConfig):
        self.config = config
        self._indent = 0
        self._output: List[str] = []

    def compile(self, source: str, filename: str = "<string>") -> CompileResult:
        result = CompileResult()
        try:
            tree = python_ast.parse(source, filename=filename)
            self._output = []
            self._indent = 0

            self._emit("--!strict")
            self._emit("-- Generated by MERO Fallback Compiler")
            self._emit('local _RT = require(script.Parent:WaitForChild("MeroRuntime"))')
            self._emit("")

            for node in tree.body:
                self._visit(node)

            result.output = "\n".join(self._output)
            result.success = True
            result.stats = {"backend": "fallback"}
        except SyntaxError as e:
            result.errors.append(f"{filename}:{e.lineno}:{e.offset}: {e.msg}")
        except Exception as e:
            result.errors.append(str(e))

        return result

    def _emit(self, line: str):
        if line.strip():
            self._output.append("    " * self._indent + line)
        else:
            self._output.append("")

    def _visit(self, node):
        method = f"_visit_{type(node).__name__}"
        visitor = getattr(self, method, self._visit_generic)
        visitor(node)

    def _visit_generic(self, node):
        self._emit(f"-- unsupported: {type(node).__name__}")

    def _visit_FunctionDef(self, node: python_ast.FunctionDef):
        params = ", ".join(a.arg for a in node.args.args if a.arg != "self")
        self._emit(f"local function {node.name}({params})")
        self._indent += 1
        for stmt in node.body:
            self._visit(stmt)
        self._indent -= 1
        self._emit("end")
        self._emit("")

    def _visit_ClassDef(self, node: python_ast.ClassDef):
        self._emit(f"local {node.name} = {{}}")
        self._emit(f"{node.name}.__index = {node.name}")
        self._emit("")

        for item in node.body:
            if isinstance(item, python_ast.FunctionDef):
                if item.name == "__init__":
                    params = ", ".join(a.arg for a in item.args.args[1:])
                    self._emit(f"function {node.name}.new({params})")
                    self._indent += 1
                    self._emit(f"local self = setmetatable({{}}, {node.name})")
                    for stmt in item.body:
                        self._visit(stmt)
                    self._emit("return self")
                    self._indent -= 1
                    self._emit("end")
                else:
                    params = ", ".join(a.arg for a in item.args.args[1:])
                    self._emit(f"function {node.name}:{item.name}({params})")
                    self._indent += 1
                    for stmt in item.body:
                        self._visit(stmt)
                    self._indent -= 1
                    self._emit("end")
            self._emit("")

    def _visit_Return(self, node: python_ast.Return):
        if node.value:
            self._emit(f"return {self._expr(node.value)}")
        else:
            self._emit("return")

    def _visit_Assign(self, node: python_ast.Assign):
        target = self._expr(node.targets[0])
        value = self._expr(node.value)
        if "." not in target and "[" not in target:
            self._emit(f"local {target} = {value}")
        else:
            self._emit(f"{target} = {value}")

    def _visit_AugAssign(self, node: python_ast.AugAssign):
        target = self._expr(node.target)
        value = self._expr(node.value)
        op = self._binop_str(node.op)
        self._emit(f"{target} = {target} {op} {value}")

    def _visit_If(self, node: python_ast.If):
        self._emit(f"if {self._expr(node.test)} then")
        self._indent += 1
        for stmt in node.body:
            self._visit(stmt)
        self._indent -= 1
        if node.orelse:
            if len(node.orelse) == 1 and isinstance(node.orelse[0], python_ast.If):
                self._emit(f"elseif {self._expr(node.orelse[0].test)} then")
                self._indent += 1
                for stmt in node.orelse[0].body:
                    self._visit(stmt)
                self._indent -= 1
            else:
                self._emit("else")
                self._indent += 1
                for stmt in node.orelse:
                    self._visit(stmt)
                self._indent -= 1
        self._emit("end")

    def _visit_While(self, node: python_ast.While):
        self._emit(f"while {self._expr(node.test)} do")
        self._indent += 1
        for stmt in node.body:
            self._visit(stmt)
        self._indent -= 1
        self._emit("end")

    def _visit_For(self, node: python_ast.For):
        target = self._expr(node.target)
        iter_expr = self._expr(node.iter)
        self._emit(f"for _, {target} in {iter_expr} do")
        self._indent += 1
        for stmt in node.body:
            self._visit(stmt)
        self._indent -= 1
        self._emit("end")

    def _visit_Expr(self, node: python_ast.Expr):
        self._emit(self._expr(node.value))

    def _visit_Pass(self, node):
        pass

    def _visit_Break(self, node):
        self._emit("break")

    def _visit_Continue(self, node):
        self._emit("continue")

    def _expr(self, node) -> str:
        if isinstance(node, python_ast.Constant):
            if node.value is None:
                return "nil"
            if isinstance(node.value, bool):
                return "true" if node.value else "false"
            if isinstance(node.value, str):
                return f'"{node.value}"'
            return str(node.value)
        elif isinstance(node, python_ast.Name):
            if node.id == "True": return "true"
            if node.id == "False": return "false"
            if node.id == "None": return "nil"
            return node.id
        elif isinstance(node, python_ast.BinOp):
            left = self._expr(node.left)
            right = self._expr(node.right)
            op = self._binop_str(node.op)
            return f"({left} {op} {right})"
        elif isinstance(node, python_ast.Call):
            func = self._expr(node.func)
            args = ", ".join(self._expr(a) for a in node.args)
            return f"{func}({args})"
        elif isinstance(node, python_ast.Attribute):
            value = self._expr(node.value)
            if value == "self":
                return f"self.{node.attr}"
            return f"{value}.{node.attr}"
        elif isinstance(node, python_ast.Compare):
            left = self._expr(node.left)
            parts = [left]
            for op, comp in zip(node.ops, node.comparators):
                parts.append(self._cmpop_str(op))
                parts.append(self._expr(comp))
            return " ".join(parts)
        elif isinstance(node, python_ast.List):
            elts = ", ".join(self._expr(e) for e in node.elts)
            return "{" + elts + "}"
        elif isinstance(node, python_ast.Dict):
            pairs = []
            for k, v in zip(node.keys, node.values):
                pairs.append(f"[{self._expr(k)}] = {self._expr(v)}")
            return "{" + ", ".join(pairs) + "}"
        elif isinstance(node, python_ast.Subscript):
            value = self._expr(node.value)
            idx = self._expr(node.slice)
            return f"{value}[{idx} + 1]"
        elif isinstance(node, python_ast.JoinedStr):
            parts = []
            for v in node.values:
                if isinstance(v, python_ast.Constant):
                    parts.append(f'"{v.value}"')
                else:
                    parts.append(f"tostring({self._expr(v)})")
            return " .. ".join(parts) if parts else '""'
        elif isinstance(node, python_ast.FormattedValue):
            return self._expr(node.value)
        elif isinstance(node, python_ast.UnaryOp):
            operand = self._expr(node.operand)
            if isinstance(node.op, python_ast.Not):
                return f"(not {operand})"
            if isinstance(node.op, python_ast.USub):
                return f"(-{operand})"
            return operand
        elif isinstance(node, python_ast.BoolOp):
            op = " and " if isinstance(node.op, python_ast.And) else " or "
            return op.join(self._expr(v) for v in node.values)
        return f"nil --[[ {type(node).__name__} ]]"

    def _binop_str(self, op) -> str:
        ops = {
            python_ast.Add: "+", python_ast.Sub: "-",
            python_ast.Mult: "*", python_ast.Div: "/",
            python_ast.FloorDiv: "//", python_ast.Mod: "%",
            python_ast.Pow: "^", python_ast.LShift: "<<",
            python_ast.RShift: ">>",
        }
        return ops.get(type(op), "+")

    def _cmpop_str(self, op) -> str:
        ops = {
            python_ast.Eq: "==", python_ast.NotEq: "~=",
            python_ast.Lt: "<", python_ast.Gt: ">",
            python_ast.LtE: "<=", python_ast.GtE: ">=",
        }
        return ops.get(type(op), "==")
